# Update according to
# https://github.com/rundocs/jekyll-rtd-theme/releases/tag/v1.1.7
#remote_theme: rundocs/jekyll-rtd-theme@bb00646afd7f05b3f4badb32ce1710197c483dfd
theme: jekyll-rtd-theme
logo: /ro-crate/assets/img/ro-crate.svg

title: Research Object Crate (RO-Crate)
description: |
  RO-Crate is a community effort to establish a lightweight approach to
  packaging research data with their metadata. It is based on schema.org
  annotations in JSON-LD, and aims to make best-practice in formal metadata
  description accessible and practical for use in a wider variety of situations,
  from an individual researcher working with a folder of data, to large
  data-intensive computational research environments.

# carlosperate/jekyll-theme-rtd settings:
##site_author: researchobject.org community
##repo_url: "https://github.com/researchobject/ro-crate/"
##edit_on_github: true
##github_docs_folder: true
##sticky_navigation: true
##prev_next_buttons_location: bottom
##search_enabled: true
##hljs_style: github-gist


# rundocs/jekyll-rtd-theme theme settings
addons_branch: false
edit: true

author: "University of Technology Sydney, The University of Manchester UK and RO-Crate contributors"
copyright:
  since: 2019

embed: |
  <a href="https://nodejs.org/en/black-lives-matter/">#BlackLivesMatter</a>
  

addons:
  - github
  - plugins

copyright:
  revision: false


readme_index:
  with_frontmatter: true

plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-relative-links

# If you want to turn off the order prefix in toctree  
# show_sorted: false